#baseurl = "http://sample-castanet.netlify.com/mysite/"
languageCode = "fa-ir"
title = "رادیو خط فرمان"
theme = "castanet"
googleAnalytics = ""
themesdir = "theme"
paginate = "9"
shamsiDateFormat = "d MMM yyyy"


[permalinks]
  page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "درباره پادکست"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "راه‌های ارتباط"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "میزبان‌ها"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "مهمان‌ها"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "منابع"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "کتاب‌ها"
    identifier = "books"
    url = "/books"
    parent = "resources"
[[Menu.Main]]
    name = "پادکست‌ها"
    identifier = "podcasts"
    url = "/podcasts"
    parent = "resources"
[[Menu.Main]]
    name = "مقالات"
    identifier = "articles"
    url = "/articles"
    parent = "resources"

[params]
mainSections = ["episode"]
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
enable_jumbo = "true"
#enable_jumbo = "false"
# truncate = "100"
# about_logo = "/img/hugocast.png"
copyright_notice = "This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)"
#copyright_notice = "saasasasa"
github_repo = "https://github.com"
medium_article = "https://medium.com"
itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
spotify_subscribe = "https://open.spotify.com/show/..."
castbox_subscribe = "itunes_subscribe = "
#google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
twitter_handle = "https://twitter.com/khatefarman"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = " رادیو خط‌فرمان پادکستی گفت‌وگو محور با موضوعیت دواپس، زیرساخت‌های ابری، لینوکس و توسعه نرم‌افزار بوده که تلاش می‌کند هر دوهفته افراد خبره این حوزه‌ها در کنار هم جمع شده و در مورد موضوعی از پیش تعیین شده بحث کنند. "
#media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
media_prefix = "http://localhost:1313/"
disqusShortname = ""
  [params.feed]
    copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The best podcast ever" #no markdown or HTML
    itunes_author = "Matt Stratton" #no markdown or HTML
    itunes_summary = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about podcasting from the most inspiring experts to ever show up on the whole internet." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
    language = "en-us"

# [params.podlove] # https://subscribe-button.podlove.org
##    subscribe_title = ""              # fallback: site title from above
#    subscribe_subtitle = ""           # fallback: ""
#    subscribe_description = ""        # fallback: ""
#    subscribe_cover = "img/logo.jpg"  # fallback: ""
#    subscribe_color = "#585e6c"       # fallback: ""
#    subscribe_size = "medium"         # options: small, medium, big
#    subscribe_format = "rectangle"    # options: rectangle, square, cover
#    subscribe_style = "filled"        # options: filled, outline, frameless
#    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
#    subscribe_feed_type = "audio"     # options: audio, video
#    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    github = "khatefarman"
#    gitlab = "mattstratton"
#    facebook = "Arresteddevops"
#    facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "khatefarman"
    twitter_domain = "khatefarman.github.io" # This domain shows in twitter cards as "View on `twitter_domain`"
#    googleplus = "ArrestedDevOps"
#    pinterest = "nozzleio"
#    instagram = "nozzleio"
#    youtube = "arresteddevops"
#   linkedin = "mattstratton"
    medium = "khatefarman"
    telegram = "khatefarman"
  [params.authors]
    [params.authors.Matt]
      name	= "بهروز حسن بیگی"
      thumbnail = "img/host/behrooz.jpg"
      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
      [params.authors.Matt.social]
        github = "mattstratton"
        facebook = "matt.stratton"
        twitter = "mattstratton"
        linkedin = "mattstratton"
        homepage = "https://www.mattstratton.io"
        pinterest = "mattstratton"
        instagram = "instagram"
        youtube = "mattstratton"
    [params.authors.Trevor]
			name = "امیرحسین گودرزی"
			thumbnail = "img/host/amir.jpg"
			bio = ""
				[params.authors.Trevor.social]
					twitter = "trevorghess"
    [params.authors.Bridget]
      name = "حسین فرمانی"
      thumbnail = "img/host/hossein.jpg"
      bio = ""
      [params.authors.Bridget.social]
        twitter = "bridgetkromhout"

    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
