baseurl = "https://khatefarman.github.io/"
languageCode = "fa-ir"
title = "رادیو خط فرمان"
theme = "castanet"
googleAnalytics = ""
themesdir = "theme"
paginate = "9"
# Hoor date format
shamsiDateFormat = "d MMM yyyy"


[permalinks]
  page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# Menu section
[[Menu.Main]]
    name = "درباره پادکست"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "راه‌های ارتباط"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "میزبان‌ها"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "مهمان‌ها"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "منابع"
    identifier = "resources"
    url = "#!"

[[Menu.Main]]
    name = "کتاب‌ها"
    identifier = "books"
    url = "/books"
    parent = "resources"
[[Menu.Main]]
    name = "پادکست‌ها"
    identifier = "podcasts"
    url = "/podcasts"
    parent = "resources"
[[Menu.Main]]
    name = "مقالات"
    identifier = "articles"
    url = "/articles"
    parent = "resources"

[params]
mainSections = ["episode"]
site_theme = "grey"
favicon = 'img/favicon.ico'
site_layout = "row" # or grid
# the section in top place with images and name of the hosts
enable_jumbo = "true" # or false
# The number of characters to truncate the summary on the row layout. This can be overridden per-episode as well. The default value (if not set) is 600 characters.	
# truncate = "100" 
about_logo = "img/assets/logo.png"
copyright_notice = "This work is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)"
# github_repo = "https://github.com"
# medium_article = "https://medium.com"
itunes_subscribe = "http://itunes.apple.com/us/"
spotify_subscribe = "https://open.spotify.com/show/0mioSMTMrb6BIwjSJ16YXc"
castbox_subscribe = "https://castbox.fm/channel/id2454096"
#google_play_subscribe = "https://goo.gl/app/"
soundcloud_subscribe = "https://soundcloud.com/khatefarman"
twitter_handle = "https://twitter.com/khatefarman"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = " رادیو خط‌فرمان پادکستی گفت‌وگو محور با موضوعیت دواپس، زیرساخت‌های ابری، لینوکس و توسعه نرم‌افزار بوده که تلاش می‌کند هر دوهفته افراد خبره این حوزه‌ها در کنار هم جمع شده و در مورد موضوعی از پیش تعیین شده بحث کنند. "
media_prefix = "https://khatefarman.github.io/"
disqusShortname = "khatefarman"
  [params.feed]
    copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "بحث و گفت‌ و گوی دواپس‌ها" #no markdown or HTML
    itunes_author = "khatefarman" #no markdown or HTML
    itunes_summary = "رادیو خط‌فرمان پادکستی گفت‌وگو محور با موضوعیت دواپس، زیرساخت‌های ابری، لینوکس و توسعه نرم‌افزار بوده که تلاش می‌کند هر دوهفته افراد خبره این حوزه‌ها در کنار هم جمع شده و در مورد موضوعی از پیش تعیین شده بحث کنند. " 
    itunes_owner_name = ""
    itunes_owner_email = "amir007ag@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://khatefarman.github.io/img/assets/logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
    language = "fa-ir"
    explicit = "no"

# [params.podlove] # https://subscribe-button.podlove.org
##    subscribe_title = ""              # fallback: site title from above
#    subscribe_subtitle = ""           # fallback: ""
#    subscribe_description = ""        # fallback: ""
#    subscribe_cover = "img/logo.jpg"  # fallback: ""
#    subscribe_color = "#585e6c"       # fallback: ""
#    subscribe_size = "medium"         # options: small, medium, big
#    subscribe_format = "rectangle"    # options: rectangle, square, cover
#    subscribe_style = "filled"        # options: filled, outline, frameless
#    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
#    subscribe_feed_type = "audio"     # options: audio, video
#    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    github = "khatefarman"
#    gitlab = "mattstratton"
#    facebook = "Arresteddevops"
#    facebook_admin = ["500557137","1234"] # This needs to be one or more page admins to get domain insights
    twitter = "khatefarman"
    twitter_domain = "khatefarman.github.io" # This domain shows in twitter cards as "View on `twitter_domain`"
#    googleplus = "-"
#    pinterest = "-"
#    instagram = "-"
#    youtube = "-"
#   linkedin = "-"
    medium = "khatefarman"
    telegram = "khatefarman"
  [params.authors]
    [params.authors.behrooz]
      name	= "بهروز حسن بیگی"
      thumbnail = "img/host/behrooz.jpg"
      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
      [params.authors.behrooz.social]
        github = "mattstratton"
        facebook = "matt.stratton"
        twitter = "mattstratton"
        linkedin = "mattstratton"
        homepage = "https://www.mattstratton.io"
        pinterest = "mattstratton"
        instagram = "instagram"
        youtube = "mattstratton"
    [params.authors.amir]
			name = "امیرحسین گودرزی"
			thumbnail = "img/host/amir.jpg"
			bio = ""
				[params.authors.amir.social]
          github = "numb95"
          twitter = "goodarzi_ah"
          linkedin = "amirhosseingoodarzi"
          homepage = "https://goodarzi.net"
          instagram = "farxmani"    
    [params.authors.hossein]
      name = "حسین فرمانی"
      thumbnail = "img/host/hossein.jpg"
      bio = "حسین فرمانی هستم یک علاقه مند به دنیای باینری از نوع آزادش و تمام اتفاقاتی که توش ممکنه بیفته. فرمانی صدام میکنند ولی صمیمی تر ها با حسین راحت تر هستن. توی دانشگاه مهندسی کامپیوتر گرایش نرم افزار خوندم از اونجایی که از سه چهار سالگی تو خونمون کامپیوتر داشتم با کامپیوتر بزرگ شدم و تقریبا بخش عمده ای از عمرم رو با کامپیوتر سرگرم بودم و خوب علاقم به این مورد باعث شد که در تمام این سال هایی که بزرگتر میشدم این عشق پا برجا بمونه و روز به روز بیشتر و بیشتر درگیرش باشم تا امروز که با این عشق کسب درآمد و گذران زندگی میکنم"
      [params.authors.hossein.social]
        github = "farmanih"
        twitter = "Farxmani"
        linkedin = "farmanih"
        homepage = "https://farmanih.ir"
        instagram = "farxmani"

#    [params.links]
#      [params.links.ado]
#        name = "Arrested DevOps"
#        url = "https://www.arresteddevops.com"
#     [params.links.ffs]
#        name = "Food Fight Show"
#        url = "https://foodfightshow.org"
#     [params.links.sdt]
#        name = "Software Defined Talk"
#        url = "https://cote.io/podcasts/sdt/"


